# Generated by Django 5.2 on 2026-04-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=201, verbose_name="Título"),
        ),
    ]
