# Generated by Django 5.2.8 on 2026-04-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalestranteCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=150)),
                ('dia_apresentacao', models.IntegerField(help_text='Dia 1, 2, etc.')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='coin/palestrantes/')),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Palestrante CoIn',
                'verbose_name_plural': 'Palestrantes CoIn',
            },
        ),
        migrations.CreateModel(
            name='PatrocinadorCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='coin/patrocinadores/')),
                ('site_url', models.URLField(blank=True, null=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
        ),
    ]
